
package view;

import repository.QuanLyThongKeController;

public class Form_ThongKe extends javax.swing.JPanel {

    /** Creates new form Form_ThongKe */
    public Form_ThongKe() {
        initComponents();
        QuanLyThongKeController controller = new QuanLyThongKeController();
        controller.setDateToChart(jpanelView1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelRoot = new javax.swing.JPanel();
        jpanelView1 = new javax.swing.JPanel();
        jpanelView2 = new javax.swing.JPanel();

        jpanelView1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpanelView1Layout = new javax.swing.GroupLayout(jpanelView1);
        jpanelView1.setLayout(jpanelView1Layout);
        jpanelView1Layout.setHorizontalGroup(
            jpanelView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        jpanelView1Layout.setVerticalGroup(
            jpanelView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        jpanelView2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpanelView2Layout = new javax.swing.GroupLayout(jpanelView2);
        jpanelView2.setLayout(jpanelView2Layout);
        jpanelView2Layout.setHorizontalGroup(
            jpanelView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpanelView2Layout.setVerticalGroup(
            jpanelView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpanelRootLayout = new javax.swing.GroupLayout(jpanelRoot);
        jpanelRoot.setLayout(jpanelRootLayout);
        jpanelRootLayout.setHorizontalGroup(
            jpanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpanelView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpanelView2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpanelRootLayout.setVerticalGroup(
            jpanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jpanelView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpanelRoot;
    private javax.swing.JPanel jpanelView1;
    private javax.swing.JPanel jpanelView2;
    // End of variables declaration//GEN-END:variables

}
